
version: '3'
services:
  tomcat:
    image: tomcat
    container_name: tomcat
    hostname: tomcat
    networks:
        container-link:
            ipv4_address: 172.18.0.3
    volumes:
    - /opt/webapps:/usr/local/tomcat/webapps
    ports:
    - 8080:8080
    depends_on:
    - "postgres"
    restart: always

  postgres:
    image: postgres:alpine
    container_name: postgres
    hostname: postgres
    networks:
        container-link:
            ipv4_address: 172.18.0.2
    volumes:
    - /opt/postgresql:/var/lib/postgresql
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_DB=demodb
    - POSTGRES_PASSWORD=password
    - PGDATA=/var/lib/postgresql/data/pgdata
    restart: always

networks:
  default:
    external:
      name: bridge
  container-link:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: "172.18.0.0/24"
